### ISSUE TITLE
Error on startup after add client from admin console

### ISSUE THREAD

**Issue by zohen** [liveoak-io/liveoak#455]
```
2015-06-30 06:28:03,432 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) JBAS017534: Registered web context: /auth
2015-06-30 06:28:03,782 INFO  [org.rhq.metrics.restServlet.RHQMetricsRestApp] (MSC service thread 1-4) RHQ Metrics starting ..
2015-06-30 06:28:03,783 INFO  [org.jboss.resteasy.spi.ResteasyDeployment] (MSC service thread 1-4) Deploying javax.ws.rs.core.Application: class org.rhq.metrics.restServlet.RHQMetricsRestApp$Proxy$_$$_WeldClientProxy
2015-06-30 06:28:03,783 INFO  [org.rhq.metrics.restServlet.RHQMetricsRestApp] (MSC service thread 1-4) RHQ Metrics starting ..
2015-06-30 06:28:03,790 INFO  [stdout] (MSC service thread 1-4) Using a backend implementation of org.rhq.metrics.impl.memory.MemoryMetricsService
2015-06-30 06:28:03,856 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) JBAS017534: Registered web context: /rhq-metrics
2015-06-30 06:28:05,506 ERROR [io.liveoak.spi.resource.config.ConfigRootResource] (InitializeResourceService starter - application-clients) Unable to create child config resource for io.liveoak.application.clients.ApplicationClientsResource: java.lang.NullPointerException
    at io.liveoak.application.clients.SimpleApplicationClientResource.<init>(SimpleApplicationClientResource.java:59)
    at io.liveoak.application.clients.ApplicationClientsResource.createApplicationClient(ApplicationClientsResource.java:81)
    at io.liveoak.application.clients.ApplicationClientsResource.createMember(ApplicationClientsResource.java:59)
    at io.liveoak.spi.resource.config.ConfigRootResource.lambda$initializeProperties$2(ConfigRootResource.java:41) [liveoak-spi.jar:1.0.1.Final-SNAPSHOT]
    at io.liveoak.spi.resource.config.ConfigRootResource$$Lambda$38/1647789218.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249) [rt.jar:1.8.0_45]
    at io.liveoak.spi.resource.config.ConfigRootResource.initializeProperties(ConfigRootResource.java:39) [liveoak-spi.jar:1.0.1.Final-SNAPSHOT]
    at io.liveoak.application.clients.ApplicationClientsResource.initializeProperties(ApplicationClientsResource.java:48)
    at io.liveoak.container.extension.ConfigPersistingWrappingResource.initializeProperties(ConfigPersistingWrappingResource.java:54) [liveoak-container.jar:1.0.1.Final-SNAPSHOT]
    at io.liveoak.container.extension.application.ConfigRootResourceWrappingResource.initializeProperties(ConfigRootResourceWrappingResource.java:59) [liveoak-container.jar:1.0.1.Final-SNAPSHOT]
    at io.liveoak.container.extension.service.InitializeResourceService.lambda$start$38(InitializeResourceService.java:43) [liveoak-container.jar:1.0.1.Final-SNAPSHOT]
    at io.liveoak.container.extension.service.InitializeResourceService$$Lambda$36/224215859.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_45]

2015-06-30 06:28:05,551 INFO  [io.liveoak.security.policy.acl.impl.AclPolicyConfigurator] (InitializeResourceService starter - acl-policy) AclPolicy configuration successfully updated
2015-06-30 06:28:05,628 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 30) JBAS018559: Deployed "rhq-metrics-rest-0.2.4.Alpha01-liveoak.war" (runtime-name : "rhq-metrics-rest-0.2.4.Alpha01-liveoak.war")
2015-06-30 06:28:05,629 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 30) JBAS018559: Deployed "auth-server.war" (runtime-name : "auth-server.war")
2015-06-30 06:28:05,749 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015961: Http management interface listening on http://127.0.0.1:9990/management
2015-06-30 06:28:05,749 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015951: Admin console listening on http://127.0.0.1:9990
2015-06-30 06:28:05,750 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: WildFly 8.2.0.Final "Tweek" started in 7387ms - Started 836 of 897 services (106 services are lazy, passive or on-demand)


```

**Comment by kenfinnigan** [comment]
Are you using an external Keycloak instance?

The issue appears to be caused by LiveOak expecting Client Scope mappings to be present in Keycloak, and they're not, which is why we see the NPE

**Comment by zohen** [comment]
I use internal Keycloak (http://localhost:5000/auth/admin/). All added clients are presents in Keycloak, but not presents at LiveOak.
